# Generated by Django 5.1.5 on 2025-01-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company',
            new_name='current_company',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='position',
            new_name='current_job_title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='certifications',
            field=models.TextField(blank=True, help_text='Enter certifications separated by commas'),
        ),
        migrations.AddField(
            model_name='user',
            name='industry',
            field=models.CharField(blank=True, choices=[('it', 'Information Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('consulting', 'Consulting'), ('marketing', 'Marketing'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='mentorship_availability',
            field=models.CharField(blank=True, choices=[('available', 'Available for Mentorship'), ('limited', 'Limited Availability'), ('unavailable', 'Not Available')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, help_text='Enter skills separated by commas'),
        ),
        migrations.AddField(
            model_name='user',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('alumni', 'Alumni'), ('student', 'Student')], default='student', max_length=10),
        ),
    ]
