# Generated by Django 5.1.5 on 2025-01-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_update_superuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('alumni', 'Alumni'), ('student', 'Student')], default='student', max_length=10),
        ),
    ]
