# Generated by Django 5.1.5 on 2025-01-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobposting_options_jobposting_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, help_text='Required years of experience'),
        ),
    ]
