# Generated by Django 5.1.5 on 2025-01-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobposting_years_of_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='years_of_experience',
        ),
    ]
