# Generated by Django 5.1.5 on 2025-01-23 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='success_stories/additional/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='success.successstory')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
