# Generated by Django 5.1.5 on 2025-01-23 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0003_remove_successstory_likes_delete_storyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='success_stories/additional/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_images', to='success.successstory')),
            ],
            options={
                'verbose_name_plural': 'Additional Images',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='successstory',
            name='additional_images',
            field=models.ManyToManyField(blank=True, to='success.storyimage'),
        ),
    ]
