# Generated by Django 5.1.5 on 2025-01-23 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0004_storyimage_successstory_additional_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='successstory',
            name='additional_images',
        ),
        migrations.DeleteModel(
            name='StoryImage',
        ),
    ]
